[project]
name = "myosuite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "brax>=0.13.0",
    "flatten-dict>=0.4.2",
    "gymnasium>=1.2.0",
    "jax[cuda12]==0.6.0",
    "mujoco>=3.3.5",
    "mujoco-mjx[warp]>=3.3.5",
    "playground>=0.0.5",
]
