# This workflow will install Python dependencies, run tests

name: Python application

on:
  push:
    branches: [ "main" , "dev"]
    paths-ignore:
      - "docs/**"
      - "**/README.md"

  pull_request:
    branches: [ "main" , "dev"]
    paths-ignore:
      - "docs/**"
      - "**/README.md"

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    env:
      DISPLAY: :0
  
    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"     

    - name: Enable Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        auto-activate-base: false
    - name: Test Conda
      run: |
          conda info
          CONDA_DEFAULT_ENV=test_myosuite
          conda create --name $CONDA_DEFAULT_ENV python=3.8 -y
          source /usr/local/miniconda/etc/profile.d/conda.sh
          conda activate $CONDA_DEFAULT_ENV

#     - name: Prepare MacOS
#       if: ${{ runner.os == 'macOS' }}
#       run: |
#         brew install --cask xquartz
#         brew install hdf5        
#         export CPATH="/opt/homebrew/include/"
#         export HDF5_DIR=/opt/homebrew/
#         pip3 install h5py --only-binary h5py
    - name: Install dependencies
      run: |
        export SYSTEM_VERSION_COMPAT=0
        source /usr/local/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_DEFAULT_ENV
        python3 -m pip install --upgrade pip
        pip3 install -e .
      
    - name: Run Test environment
      run: |
        source /usr/local/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_DEFAULT_ENV
        python3 -m myosuite.tests.test_myo