import cv2
import numpy as np
import os

def images_to_video(image_array, output_filename="output.mp4", fps=30):
    """ This function was generated by ChatGPT.
    Convert an array of images (NumPy arrays) into an MP4 video and open it."""
    
    if len(image_array) == 0:
        print("No images to process.")
        return
    
    # Get dimensions from the first image
    height, width, layers = image_array[0].shape

    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Codec for .mp4
    video_writer = cv2.VideoWriter(output_filename, fourcc, fps, (width, height))

    for img in image_array:
        video_writer.write(img)

    video_writer.release()

    print(f"Video saved as {output_filename}")

    # Automatically open the video (cross-platform)
    if os.name == "nt":  # Windows
        os.startfile(output_filename)
    elif os.name == "posix":  # macOS/Linux
        os.system(f"open {output_filename}" if "darwin" in os.sys.platform else f"xdg-open {output_filename}")
